### ISSUE TITLE
All-New UI

### ISSUE THREAD

**Issue by alexlafroscia** [alexlafroscia/atom-ember-cli-helper#12]
This plugin is just about as old as Atom itself, and the UI is awful.  I know it.  You know it.  Everyone knows it.

I'm hoping to find either a UI framework to build on top of, or to find build myself something that can then be extended by other packages to create a unified system for commands that are being run/monitored through Atom.   We'll see what happens.

**Comment by karelvuong** [comment]
Hey @alexlafroscia, what are your thoughts on improving the UI? Do you have a direction you want to go with this?

**Comment by alexlafroscia** [comment]
Not 100% sure. I'm not really happy with the start/stop mechanism right now, and I think the way that each line is printed out could be improved. Do you have some suggestions?
