### ISSUE TITLE
nvm support

### ISSUE THREAD

**Issue by Xobb** [alexlafroscia/atom-ember-cli-helper#16]
Hello, any plans to support NVM? I didn't install ember globally because I maintain different node versions via nvm.

**Comment by alexlafroscia** [comment]
Does it not work? I use Ember with NVM as well and haven't had an issue

**Comment by donahchoo** [comment]
It doesn't work because atom-ember-cli-help can't find ember even though its on PATH.

```
   Failed to spawn command /usr/local/bin/ember.  Make sure /usr/local/bin/ember is installed on your PATH.
```

but it is on my path:

```
echo $PATH
/Users/me/.nvm/versions/node/v0.12.7/bin
``` 

```
which ember
/Users/me/.nvm/versions/node/v0.12.7/bin/ember
```

**Comment by donahchoo** [comment]
To work around this I tired to create a link to /usr/local/bin/ember, but then the plugin complains about not finding node...

```
env node: no such file or directory
```
