### ISSUE TITLE
Alternate path option

### ISSUE THREAD

**Issue by CreativLogic** [alexlafroscia/atom-ember-cli-helper#5]
I run my project root with an `api` directory and an `ember` directory where the ember-cli project is held. It would be nice to be able to tell atom-ember-cli-helper where to execute the command so that you don't get:

![screen shot 2014-12-29 at 9 03 14 am](https://cloud.githubusercontent.com/assets/3345374/5569165/8c2eb89c-8f39-11e4-9ea3-f72eb1e21a88.png)

**Comment by CreativLogic** [comment]
Yes, that's correct. Thanks for looking!

**Comment by alexlafroscia** [comment]
I've been out of the Atom plugin loop for a while -- can you do per-project settings?

**Comment by alexlafroscia** [comment]
Hey @CreativLogic, I just figured I'd let you know that I'm working on this right now.  My plan is to just allow for an Ember sub-directory settings, which you can enable on a per-project basis using [`project-manager`](https://atom.io/packages/project-manager).
